"""
End-to-end parsing pipeline test.

Reads test_data/mixed_schema.tfrecord (generated by test_data/generate.py),
which contains 3 old-schema records followed by 3 new-schema records, and
verifies that transforms.expand_bytes correctly parses both schemas.

Old-schema records:  no pi_aux_dist / mcts_value_dist → sentinels + flags=False
New-schema records:  both fields present → actual values + flags=True
"""

import os
import unittest

import numpy as np
from tfrecord import reader as tfreader

import transforms
from constants import BOARD_LEN, BLACK, WHITE, NUM_MOVES, NUM_V_BUCKETS

# Path to pre-generated fixture (relative to python/).
_FIXTURE = os.path.join(
    os.path.dirname(__file__), "..", "test_data", "mixed_schema.tfrecord"
)

# Indices into the expand() return tuple (kept in sync with transforms.py).
_IDX_INPUT = 0
_IDX_INPUT_GLOBAL_STATE = 1
_IDX_COLOR = 2
_IDX_KOMI = 3
_IDX_SCORE = 4
_IDX_SCORE_ONE_HOT = 5
_IDX_POLICY = 6
_IDX_POLICY_AUX = 7
_IDX_POLICY_AUX_DIST = 8
_IDX_HAS_PI_AUX_DIST = 9
_IDX_OWN = 10
_IDX_Q6 = 11
_IDX_Q16 = 12
_IDX_Q50 = 13
_IDX_Q6_SCORE = 14
_IDX_Q16_SCORE = 15
_IDX_Q50_SCORE = 16
_IDX_GAME_OUTCOME = 17
_IDX_MCTS_VALUE_DIST = 18
_IDX_HAS_MCTS_VALUE_DIST = 19
_NUM_OUTPUTS = 20


class PipelineTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        """Load and expand all 6 records once for the entire test class."""
        if not os.path.exists(_FIXTURE):
            raise unittest.SkipTest(
                f"Fixture not found: {_FIXTURE}. "
                "Run python/test_data/generate.py to create it."
            )
        # Uncompressed fixture; expand_bytes returns numpy 20-tuples directly.
        cls.records = [
            transforms.expand_bytes(bytes(view))
            for view in tfreader.tfrecord_iterator(_FIXTURE, compression_type=None)
        ]

    def test_fixture_has_six_records(self):
        self.assertEqual(len(self.records), 6)

    def test_all_records_have_correct_output_count(self):
        for rec in self.records:
            self.assertEqual(len(rec), _NUM_OUTPUTS)

    def test_old_schema_has_pi_aux_dist_false(self):
        for i in range(3):
            with self.subTest(record=i):
                self.assertFalse(self.records[i][_IDX_HAS_PI_AUX_DIST])

    def test_old_schema_has_mcts_value_dist_false(self):
        for i in range(3):
            with self.subTest(record=i):
                self.assertFalse(self.records[i][_IDX_HAS_MCTS_VALUE_DIST])

    def test_old_schema_policy_aux_dist_is_zeros(self):
        for i in range(3):
            with self.subTest(record=i):
                dist = self.records[i][_IDX_POLICY_AUX_DIST]
                self.assertEqual(dist.shape, (NUM_MOVES,))
                np.testing.assert_array_equal(
                    dist, np.zeros(NUM_MOVES, dtype=np.float32)
                )

    def test_old_schema_mcts_value_dist_is_zeros(self):
        for i in range(3):
            with self.subTest(record=i):
                dist = self.records[i][_IDX_MCTS_VALUE_DIST]
                self.assertEqual(dist.shape, (NUM_V_BUCKETS,))
                np.testing.assert_array_equal(
                    dist, np.zeros(NUM_V_BUCKETS, dtype=np.int32)
                )

    def test_old_schema_standard_fields_intact(self):
        r = self.records[0]
        self.assertEqual(r[_IDX_INPUT].shape, (BOARD_LEN, BOARD_LEN, 15))
        self.assertEqual(r[_IDX_POLICY].shape, (NUM_MOVES,))
        self.assertEqual(r[_IDX_SCORE_ONE_HOT].shape[0], 800)
        self.assertEqual(r[_IDX_COLOR], BLACK)
        self.assertAlmostEqual(float(r[_IDX_SCORE]), 5.5, places=4)

    def test_new_schema_has_pi_aux_dist_true(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                self.assertTrue(self.records[i][_IDX_HAS_PI_AUX_DIST])

    def test_new_schema_has_mcts_value_dist_true(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                self.assertTrue(self.records[i][_IDX_HAS_MCTS_VALUE_DIST])

    def test_new_schema_policy_aux_dist_shape(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                dist = self.records[i][_IDX_POLICY_AUX_DIST]
                self.assertEqual(dist.shape, (NUM_MOVES,))

    def test_new_schema_mcts_value_dist_shape(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                dist = self.records[i][_IDX_MCTS_VALUE_DIST]
                self.assertEqual(dist.shape, (NUM_V_BUCKETS,))

    def test_new_schema_policy_aux_dist_sums_to_one(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                dist = self.records[i][_IDX_POLICY_AUX_DIST]
                self.assertAlmostEqual(float(dist.sum()), 1.0, places=5)

    def test_new_schema_record4_mcts_dist_values(self):
        dist = self.records[3][_IDX_MCTS_VALUE_DIST]
        self.assertEqual(int(dist[25]), 10)
        self.assertEqual(int(dist[26]), 5)
        self.assertEqual(int(dist.sum()), 15)

    def test_new_schema_record5_mcts_dist_values(self):
        dist = self.records[4][_IDX_MCTS_VALUE_DIST]
        self.assertEqual(int(dist[0]), 100)
        self.assertEqual(int(dist.sum()), 100)

    def test_new_schema_record6_mcts_dist_all_ones(self):
        dist = self.records[5][_IDX_MCTS_VALUE_DIST]
        self.assertEqual(int(dist.sum()), NUM_V_BUCKETS)
        np.testing.assert_array_equal(dist, np.ones(NUM_V_BUCKETS, dtype=np.int32))

    def test_batched_flags_correct(self):
        """Stack flags across the 6 records; first 3 should be False, last 3 True."""
        has_pi = np.array([r[_IDX_HAS_PI_AUX_DIST] for r in self.records])
        has_mv = np.array([r[_IDX_HAS_MCTS_VALUE_DIST] for r in self.records])
        np.testing.assert_array_equal(has_pi[:3], [False, False, False])
        np.testing.assert_array_equal(has_pi[3:], [True, True, True])
        np.testing.assert_array_equal(has_mv[:3], [False, False, False])
        np.testing.assert_array_equal(has_mv[3:], [True, True, True])

    def test_batched_mask_zeros_old_schema_dist(self):
        """Multiplying mcts_value_dist by has_mcts_value_dist zeros old records."""
        dist = np.stack([r[_IDX_MCTS_VALUE_DIST] for r in self.records]).astype(
            np.float32
        )
        mask = np.array(
            [r[_IDX_HAS_MCTS_VALUE_DIST] for r in self.records], dtype=np.float32
        )[:, None]
        masked = dist * mask
        np.testing.assert_array_equal(masked[:3], np.zeros((3, NUM_V_BUCKETS)))
        np.testing.assert_array_equal(masked[3:], dist[3:])


if __name__ == "__main__":
    unittest.main()
