"""
End-to-end parsing pipeline test.

Reads test_data/mixed_schema.tfrecord (generated by test_data/generate.py),
which contains 3 old-schema records followed by 3 new-schema records, and
verifies that transforms.expand correctly parses both schemas.

Old-schema records:  no pi_aux_dist / mcts_value_dist → sentinels + flags=False
New-schema records:  both fields present → actual values + flags=True
"""

import os
import unittest

import numpy as np
import tensorflow as tf

import transforms
from constants import BOARD_LEN, BLACK, WHITE, NUM_MOVES, NUM_V_BUCKETS

# Path to pre-generated fixture (relative to python/).
_FIXTURE = os.path.join(
    os.path.dirname(__file__), "..", "test_data", "mixed_schema.tfrecord"
)

# Indices into the expand() return tuple (kept in sync with transforms.py).
_IDX_INPUT = 0
_IDX_INPUT_GLOBAL_STATE = 1
_IDX_COLOR = 2
_IDX_KOMI = 3
_IDX_SCORE = 4
_IDX_SCORE_ONE_HOT = 5
_IDX_POLICY = 6
_IDX_POLICY_AUX = 7
_IDX_POLICY_AUX_DIST = 8
_IDX_HAS_PI_AUX_DIST = 9
_IDX_OWN = 10
_IDX_Q6 = 11
_IDX_Q16 = 12
_IDX_Q50 = 13
_IDX_Q6_SCORE = 14
_IDX_Q16_SCORE = 15
_IDX_Q50_SCORE = 16
_IDX_GAME_OUTCOME = 17
_IDX_MCTS_VALUE_DIST = 18
_IDX_HAS_MCTS_VALUE_DIST = 19
_NUM_OUTPUTS = 20


class PipelineTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        """Load and expand all 6 records once for the entire test class."""
        if not os.path.exists(_FIXTURE):
            raise unittest.SkipTest(
                f"Fixture not found: {_FIXTURE}. "
                "Run python/test_data/generate.py to create it."
            )
        cls.records = list(tf.data.TFRecordDataset(_FIXTURE).map(transforms.expand))
        # Eagerly unpack each record into a list of numpy arrays.
        cls.expanded = [[t.numpy() for t in rec] for rec in cls.records]

    # ------------------------------------------------------------------
    # Fixture sanity
    # ------------------------------------------------------------------

    def test_fixture_has_six_records(self):
        self.assertEqual(len(self.records), 6)

    def test_all_records_have_correct_output_count(self):
        for rec in self.records:
            self.assertEqual(len(rec), _NUM_OUTPUTS)

    # ------------------------------------------------------------------
    # Old-schema records (indices 0-2): sentinels + flags=False
    # ------------------------------------------------------------------

    def test_old_schema_has_pi_aux_dist_false(self):
        for i in range(3):
            with self.subTest(record=i):
                self.assertFalse(self.expanded[i][_IDX_HAS_PI_AUX_DIST])

    def test_old_schema_has_mcts_value_dist_false(self):
        for i in range(3):
            with self.subTest(record=i):
                self.assertFalse(self.expanded[i][_IDX_HAS_MCTS_VALUE_DIST])

    def test_old_schema_policy_aux_dist_is_zeros(self):
        for i in range(3):
            with self.subTest(record=i):
                dist = self.expanded[i][_IDX_POLICY_AUX_DIST]
                self.assertEqual(dist.shape, (NUM_MOVES,))
                np.testing.assert_array_equal(
                    dist, np.zeros(NUM_MOVES, dtype=np.float32)
                )

    def test_old_schema_mcts_value_dist_is_zeros(self):
        for i in range(3):
            with self.subTest(record=i):
                dist = self.expanded[i][_IDX_MCTS_VALUE_DIST]
                self.assertEqual(dist.shape, (NUM_V_BUCKETS,))
                np.testing.assert_array_equal(
                    dist, np.zeros(NUM_V_BUCKETS, dtype=np.int32)
                )

    def test_old_schema_standard_fields_intact(self):
        """Spot-check that standard fields still parse correctly for old records."""
        r = self.expanded[0]
        self.assertEqual(r[_IDX_INPUT].shape, (BOARD_LEN, BOARD_LEN, 15))
        self.assertEqual(r[_IDX_POLICY].shape, (NUM_MOVES,))
        self.assertEqual(r[_IDX_SCORE_ONE_HOT].shape[0], 800)  # SCORE_RANGE
        # Record 0: color=BLACK, score_margin=5.5 → game_outcome should be Win.
        self.assertEqual(r[_IDX_COLOR], BLACK)
        self.assertAlmostEqual(float(r[_IDX_SCORE]), 5.5, places=4)

    # ------------------------------------------------------------------
    # New-schema records (indices 3-5): real values + flags=True
    # ------------------------------------------------------------------

    def test_new_schema_has_pi_aux_dist_true(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                self.assertTrue(self.expanded[i][_IDX_HAS_PI_AUX_DIST])

    def test_new_schema_has_mcts_value_dist_true(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                self.assertTrue(self.expanded[i][_IDX_HAS_MCTS_VALUE_DIST])

    def test_new_schema_policy_aux_dist_shape(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                dist = self.expanded[i][_IDX_POLICY_AUX_DIST]
                self.assertEqual(dist.shape, (NUM_MOVES,))

    def test_new_schema_mcts_value_dist_shape(self):
        for i in range(3, 6):
            with self.subTest(record=i):
                dist = self.expanded[i][_IDX_MCTS_VALUE_DIST]
                self.assertEqual(dist.shape, (NUM_V_BUCKETS,))

    def test_new_schema_policy_aux_dist_sums_to_one(self):
        """Symmetry may permute the distribution but must preserve its sum."""
        for i in range(3, 6):
            with self.subTest(record=i):
                dist = self.expanded[i][_IDX_POLICY_AUX_DIST]
                self.assertAlmostEqual(float(dist.sum()), 1.0, places=5)

    def test_new_schema_record4_mcts_dist_values(self):
        # Record 3 (0-indexed): mcts_dist_a has counts 10 at bucket 25, 5 at 26.
        dist = self.expanded[3][_IDX_MCTS_VALUE_DIST]
        self.assertEqual(int(dist[25]), 10)
        self.assertEqual(int(dist[26]), 5)
        self.assertEqual(int(dist.sum()), 15)

    def test_new_schema_record5_mcts_dist_values(self):
        # Record 4: mcts_dist_b has 100 at bucket 0.
        dist = self.expanded[4][_IDX_MCTS_VALUE_DIST]
        self.assertEqual(int(dist[0]), 100)
        self.assertEqual(int(dist.sum()), 100)

    def test_new_schema_record6_mcts_dist_all_ones(self):
        # Record 5: mcts_dist_c = all ones → sum = NUM_V_BUCKETS.
        dist = self.expanded[5][_IDX_MCTS_VALUE_DIST]
        self.assertEqual(int(dist.sum()), NUM_V_BUCKETS)
        np.testing.assert_array_equal(dist, np.ones(NUM_V_BUCKETS, dtype=np.int32))

    # ------------------------------------------------------------------
    # Dataset pipeline (batched) — verifies batching doesn't break flags
    # ------------------------------------------------------------------

    def test_batched_pipeline_flags_correct(self):
        """Batch all 6 records; first 3 should have flags=0, last 3 flags=1."""
        ds = tf.data.TFRecordDataset(_FIXTURE).map(transforms.expand).batch(6)
        batch = next(iter(ds))
        has_pi = batch[_IDX_HAS_PI_AUX_DIST].numpy()  # shape [6]
        has_mv = batch[_IDX_HAS_MCTS_VALUE_DIST].numpy()

        np.testing.assert_array_equal(has_pi[:3], [False, False, False])
        np.testing.assert_array_equal(has_pi[3:], [True, True, True])
        np.testing.assert_array_equal(has_mv[:3], [False, False, False])
        np.testing.assert_array_equal(has_mv[3:], [True, True, True])

    def test_batched_pipeline_mask_zeros_old_schema_dist(self):
        """Multiplying mcts_value_dist by has_mcts_value_dist zeros old records."""
        ds = tf.data.TFRecordDataset(_FIXTURE).map(transforms.expand).batch(6)
        batch = next(iter(ds))
        dist = tf.cast(batch[_IDX_MCTS_VALUE_DIST], tf.float32)  # [6, NUM_V_BUCKETS]
        mask = tf.cast(batch[_IDX_HAS_MCTS_VALUE_DIST], tf.float32)[:, None]  # [6, 1]
        masked = (dist * mask).numpy()

        # Old records (rows 0-2) → all zeros after masking.
        np.testing.assert_array_equal(masked[:3], np.zeros((3, NUM_V_BUCKETS)))
        # New records (rows 3-5) → unchanged.
        np.testing.assert_array_equal(masked[3:], dist.numpy()[3:])


if __name__ == "__main__":
    unittest.main()
