cc_library(
    name = "nn_wrapper",
    srcs = ["nn_wrapper.cc"],
    hdrs = ["nn_wrapper.h"],
    deps = [
        "@org_tensorflow//tensorflow/cc/saved_model:loader",
        "@org_tensorflow//tensorflow/cc/saved_model:tag_constants",
    ],
)
