cc_binary(
    name = "ucb_scratch",
    srcs = ["ucb_scratch.cc"],
    deps = [
        "//cc/core",
        "//cc/game",
        "@absl//absl/container:flat_hash_map",
        "@absl//absl/container:flat_hash_set",
        "@absl//absl/flags:flag",
        "@absl//absl/hash",
        "@absl//absl/log",
        "@absl//absl/log:check",
    ],
)
