FROM nvcr.io/nvidia/tensorflow:23.01-tf2-py3

RUN apt update && apt-get install -y \
  apt-transport-https \
  ca-certificates \
  git \
  gnupg \
  lsb-release \
  software-properties-common \
  wget \
  htop

# Install google-cloud-sdk.
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" \
  | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
  | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -y

# Install LLVM.
RUN wget https://apt.llvm.org/llvm.sh && \
  chmod +x llvm.sh && \
  ./llvm.sh 12 && \
  rm llvm.sh

# Install Bazel.
RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64 && \
  chmod +x bazelisk-linux-amd64 && \
  cp bazelisk-linux-amd64 /usr/local/lib/bazel/bin/bazel && \
  cp bazelisk-linux-amd64 /usr/bin/bazel && \
  cp bazelisk-linux-amd64 /usr/local/bin/bazel && \
  rm bazelisk-linux-amd64

# Install mimalloc
RUN git clone https://github.com/microsoft/mimalloc.git && \
  cd mimalloc && \
  mkdir -p out/release && \
  cd out/release && \
  cmake ../.. && \
  make && \
  make install && \
  cd ../../.. && \
  rm -rf mimalloc

# Setup and get p3achygo
ENV PYTHONPATH=/app/python
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ENV PATH=/usr/lib/llvm-12/bin:$PATH

WORKDIR /app

COPY requirements.txt /app

RUN pip install --upgrade pip && pip install -r /app/requirements.txt

COPY . /app

RUN cp /usr/local/lib/python3.8/dist-packages/tensorflow/libtensorflow_cc.so.2 /app/cc/tensorflow/ && \
  cp /usr/local/lib/python3.8/dist-packages/tensorflow/libtensorflow_framework.so.2 /app/cc/tensorflow/ && \
  cp -r /usr/local/lib/python3.8/dist-packages/tensorflow/include /app/cc/tensorflow/
