FROM <INSERT_NAME_HERE>
ARG RUN_ID

WORKDIR /app

RUN bazel build --config=opt //cc/shuffler:main
ENTRYPOINT ["sh", "-c", "python", "-m", "python.rl_loop.shuffle", \
  "--bin_path=/app/bazel-bin/cc/shuffler/main", "--run_id=$RUN_ID"]
