package(default_visibility = ["//visibility:public"])

cc_library(
    name = "analysis",
    srcs = ["analysis.cc"],
    hdrs = ["analysis.h"],
    deps = [
        "//cc/constants",
        "//cc/game",
        "//cc/mcts",
    ],
)
