apiVersion: batch/v1
kind: Job
metadata:
  name: p3achygo-shuffler
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: shuffler
    spec:
      containers:
      - name: player
        image: <SHUFFLE_IMAGE_NAME>
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "30Gi"
        volumeMounts:
        - name: service-credentials
          mountPath: /etc/credentials
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/service-account.json
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: UID
          value: metadata.uid
      volumes:
      - name: service-credentials
        secret:
          secretName: $SERVICE_ACCOUNT-creds
      restartPolicy: OnFailure
