apiVersion: batch/v1
kind: Job
metadata:
  name: p3achygo-train_sp_eval
spec:
  completions: 1
  template:
    metadata:
      name: train_sp_eval
    spec:
      containers:
      - name: player
        image: <TRAIN_SP_EVAL_IMAGE_NAME>
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: "16"
          requests:
            nvidia.com/gpu: 1
            cpu: "16"
